import { Suspense } from "react";
import { AppSidebar } from "@/components/shared/dashboard/app-sidebar";
import { SiteHeader } from "@/components/shared/dashboard/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import UserProvider from "@/providers/user-provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Dashboard",
    template: "%s | Dashboard",
  },
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <SidebarProvider
        style={
          {
            "--sidebar-width": "calc(var(--spacing) * 72)",
            "--header-height": "calc(var(--spacing) * 12)",
          } as React.CSSProperties
        }
      >
        <TooltipProvider>
          <Suspense fallback={<div />}>
            <AppSidebar variant="inset" />
          </Suspense>
          <SidebarInset>
            <Suspense fallback={<div />}>
              <SiteHeader />
            </Suspense>
            {children}
          </SidebarInset>
        </TooltipProvider>
      </SidebarProvider>
    </UserProvider>
  );
}
